### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sbrl** [tmiland/Nginx-Maintenance-Mode#1]
In the screenshot on the left-hand side, there's a typo. `Maintnance` should be `Maintenance` :-)

**Comment by tmiland** [comment]
> In the screenshot on the left-hand side, there's a typo. `Maintnance` should be `Maintenance` :-)

Ha! It's all in the details 🤓

Should be directed to https://github.com/alexphelps/server-error-pages/issues

Thanks for reporting!

**Comment by tmiland** [comment]
I'll see if i can make a pull request. 👍

**Comment by sbrl** [comment]
Oops! Didn't think to check if it was actually this repo I needed to open an issue against :P

Thanks :-)

**Comment by tmiland** [comment]
> Oops! Didn't think to check if it was actually this repo I needed to open an issue against :P
> 
> Thanks :-)

No worries. 👍
