### ISSUE TITLE
Feature Request - IP Exclusion

### ISSUE THREAD

**Issue by sumonst21** [tmiland/Nginx-Maintenance-Mode#2]
Is there any way to exclude certain IP's from the maintenance mode? so the maintenance mode will be on for all but listed IP's! 

Actually I Loved this somehow, I know there is other solution available with that feature but will love to use this script if i can have that feature too. :)

Many Thanks in Advance.

**Comment by tmiland** [comment]
Glad you like the script.

This sounds like a completely different script/function, and would make it far more complicated than i wish to make it. So you probably may just use "other solution" in your case unfortunately.

**Comment by thoebert** [comment]
Thanks for the scripts!

I needed exactly this feature, so I adjusted `maintenance-page.conf` slightly:

```set $maintenance 1;
if (!-f /etc/nginx/html/server-error-pages/_site/$server_name-maintenance-page_on.html) { 
   set $maintenance 0;
}
if ($internal = 1) {
  set $maintenance 0;
}
if ($maintenance = 1) {
  return 503;
}
error_page 503 @maintenance;
location @maintenance
{
  rewrite ^(.*)$ /$server_name-maintenance-page_on.html break;
  root /etc/nginx/html/server-error-pages/_site;
}
```

And included the following `maintenance-allowed-ips.conf` into my `nginx.conf`

```
geo $internal {
    # default return maintenance page
    default 0;

    # allow this to access
    1.2.3.4/32 1; 
    2.3.4.5/32 1; 
}
```

**Comment by sumonst21** [comment]
> Thanks for the scripts!
> 
> I needed exactly this feature, so I adjusted `maintenance-page.conf` slightly:
> 
> ```
> if (!-f /etc/nginx/html/server-error-pages/_site/$server_name-maintenance-page_on.html) { 
>    set $maintenance 0;
> }
> if ($internal = 1) {
>   set $maintenance 0;
> }
> if ($maintenance = 1) {
>   return 503;
> }
> error_page 503 @maintenance;
> location @maintenance
> {
>   rewrite ^(.*)$ /$server_name-maintenance-page_on.html break;
>   root /etc/nginx/html/server-error-pages/_site;
> }
> ```
> 
> And included the following `maintenance-allowed-ips.conf` into my `nginx.conf`
> 
> ```
> geo $internal {
>     # default return maintenance page
>     default 0;
> 
>     # allow this to access
>     1.2.3.4/32 1; 
>     2.3.4.5/32 1; 
> }
> ```

Congrates, but if i go this far doing manually, then i woudn't use this repo either 😄
